# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.View = PlotWidget(self.centralwidget)
        self.View.setObjectName("View")
        self.gridLayout.addWidget(self.View, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_Dicom = QtWidgets.QAction(MainWindow)
        self.actionOpen_Dicom.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/asemi/Downloads/file_open_FILL0_wght400_GRAD200_opsz48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Dicom.setIcon(icon)
        self.actionOpen_Dicom.setObjectName("actionOpen_Dicom")
        self.actionZoom = QtWidgets.QAction(MainWindow)
        self.actionZoom.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/asemi/Downloads/search_FILL1_wght600_GRAD200_opsz48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon1)
        self.actionZoom.setObjectName("actionZoom")
        self.actionaddPoints = QtWidgets.QAction(MainWindow)
        self.actionaddPoints.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/asemi/Downloads/shape_line_FILL0_wght400_GRAD200_opsz48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionaddPoints.setIcon(icon2)
        self.actionaddPoints.setObjectName("actionaddPoints")
        self.actiondeleteShape = QtWidgets.QAction(MainWindow)
        self.actiondeleteShape.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/asemi/Downloads/delete_FILL0_wght400_GRAD200_opsz48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondeleteShape.setIcon(icon3)
        self.actiondeleteShape.setObjectName("actiondeleteShape")
        self.toolBar.addAction(self.actionaddPoints)
        self.toolBar.addAction(self.actiondeleteShape)
        self.toolBar.addAction(self.actionZoom)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpen_Dicom)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen_Dicom.setText(_translate("MainWindow", "Open Dicom"))
        self.actionZoom.setText(_translate("MainWindow", "Zoom"))
        self.actionaddPoints.setText(_translate("MainWindow", "addPoints"))
        self.actiondeleteShape.setText(_translate("MainWindow", "deleteShape"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
